/**
 * @brief This file contains themes that are used to
 * style different components.
 */
export default {
  FONT_SIZE_EXTRA_SMALL: 20,
  FONT_SIZE_SMALL: 30,
  FONT_SIZE_MEDIUM: 40,
  FONT_SIZE_LARGE: 50,
  PADDING_SMALL: 10,
  PADDING_MEDIUM: 15,
  ROUNDING_EXTRA_SMALL: 5,
  ROUNDING_SMALL: 15,
  ROUNDING_MEDIUM: 30,
  ROUNDING_LARGE: 50,
  DEFAULT_FONT: "Roboto Slab",
  MARGIN_SMALL: 7,
  MARGIN_MEDIUM: 15,
  MARGIN_LARGE: 25,
  LIGHT_BLUE: "#3E9EFE",
  PINK: "#BF69E2",
  PURPLE: "#383E6E",
  DARK_PURPLE: "#081842",
  SHADOW_OFFSET: { width: 0, height: 4 },
  SHADOW_OPACITY: 0.35,
  BLUE_GRADIENT: ["#4DA6FF", "#377DC2"],
  PINK_GRADIENT: ["#BF69E2", "#C3518D"],
};
