export default {
    FONT_SIZE_EXTRA_SMALL: 15,
    FONT_SIZE_SMALL: 30,
    FONT_SIZE_MEDIUM: 35,
    FONT_SIZE_LARGE: 80,
    PADDING_SMALL: 10,
    ROUNDING_SMALL: 15,
    ROUNDING_LARGE: 50,
    DEFAULT_FONT: 'Ramaraja',
    MARGIN_SMALL: 7,
    MARGIN_MEDIUM: 15,
    LIGHT_BLUE: '#3E9EFE',
    PINK: "#BF69E2",
    PURPLE: "#383E6E",
    SHADOW_OFFSET: {width: 0, height: 4,},
    SHADOW_OPACITY: 0.35
}